use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Q14/PrivateSpecs.git'
platform :ios, '8.0'

target 'QJRouter_Example' do
  pod 'QJRouter', :path => '../'

  target 'QJRouter_Tests' do
    inherit! :search_paths

    
  end
end
